parameters:
#    events_manager_event.example.class: EventsManager\EventBundle\Example

services:
#    events_manager_event.example:
#        class: %events_manager_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
