MyConventions_accueil:
    pattern: /MyConventions/
    defaults: { _controller: MyConventionsListBundle:List:index }
    
MyConventions_ajouter:
    pattern: /MyConventions/ajouter/
    defaults: { _controller: MyConventionsListBundle:List:ajouter }

MyConventions_convention:
    pattern: /MyConventions/convention/{id}
    defaults: { _controller: MyConventionsListBundle:List:consulter }

MyConventions_editer:
    pattern: /MyConventions/edition/{id}
    defaults: { _controller: MyConventionsListBundle:List:editer }

MyConventions_supprimer:
    pattern: /MyConventions/suppression/{id}
    defaults: { _controller: MyConventionsListBundle:List:supprimer }