parameters:
#    my_conventions_list.example.class: MyConventions\ListBundle\Example

services:
#    my_conventions_list.example:
#        class: %my_conventions_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     my_conventions_list.fichier:
         class: MyConventions\ListBundle\Fichier\MyConventionsFichier
